### ISSUE TITLE
El tiempo límite se debe comprobar 'Server side'

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-quizaccess_quiztimer#34]
Cuando entras a un cuestionario puedes salir y el tiempo se pausa, por ejemplo:

- Creas un cuestionario con tiempo límite de 1 minuto por pregunta
- Un alumno entra, está 10 segundos en la pregunta y sale del cuestionario
- Cuando vuelve a entrar después de un tiempo el reloj marca 50 segundos, en vez de haber terminado

El tiempo límite se debería calcular desde que el alumno entra en la pregunta/categoría/página sin que se pause al salir, al igual que hace Moodle con el límite de tiempo por cuestionario.

**Comment by jmineroisyc** [comment]
Buenas,
El temporizador de moodle no es totalmente server side, si tu cuando empiezas un quiz editar en tu ordenador el tiempo, el temporizador de moodle se actualiza.

**Comment by jmineroisyc** [comment]
Como puedes ver, al hacerlo y actualizar un par de veces ya el tiempo se rompe y se mantiene con ese tiempo. 
[Grabación de pantalla desde 08-11-24 10:43:10.webm](https://github.com/user-attachments/assets/a7a75b4a-afd4-45eb-b5c1-f750540d7d74)

**Comment by LuksAO** [comment]
@jmineroisyc Gracias tienes razón.
