### ISSUE TITLE
Selector activo cuando no se tiene marcado usar límite de tiempo

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-quizaccess_quiztimer#38]
Buenas,

Al intentar usar este plugin, observamos que sin tener habilitado el Límite de tiempo, el selector está habilitado, cosa que hace que:

1. Despista a nivel de usabilidad.
2. El cuestionario aplique el límite de 0, por tanto, cuando se cargan las preguntas, enseguida se transmiten.

![Selecció_1362](https://github.com/user-attachments/assets/ff75b448-d9d0-4f78-b9fb-034f486887a1)

Un saludo

**Comment by jmineroisyc** [comment]
Buenas,
En mis pruebas el selector esta desabilitado.
Que navegador usas?

**Comment by tmas0** [comment]
Firefox, y lo he probado en 2 instalaciones diferentes. Reviso de nuevo.

**Comment by tmas0** [comment]
Confirmado que me pasa tanto con Firefox como con Chrome. La versión del plugin es la que está publicada en la rama main.

**Comment by jmineroisyc** [comment]
Buenas @tmas0 ,
Sigo mirando pero en todos lados me sale desactivado ese selector cuando se elige una de las tres opciones (Seccion , pregunta y pagina)
![image](https://github.com/user-attachments/assets/8607dc9c-bcfd-475a-bda1-aefa2c90fce8)

Te sale algún error por consola al ir cambiando desde el selector? En esas 3 opciones debería estar todo esto bloqueado :
![image](https://github.com/user-attachments/assets/4e7ca684-e26d-4c58-b856-b095f347f7e6)

Dime si te sale algún error por consola, seguiré probando mientras eso.

**Comment by tmas0** [comment]
Buenas @jmineroisyc,

Si, me sale esto:

```
Uncaught SyntaxError: expected expression, got ';'[modedit.php:5015:80](https://dev.pentec.es/hRfcSdeWQ/course/modedit.php?update=5640&return=1#)
```

Un saludo

**Comment by jmineroisyc** [comment]
Parece que no viene de este plugin ese error, seguiré mirando. Gracias por la información.

**Comment by jmineroisyc** [comment]
Buenas @tmas0 
He subido lo ultimo en la rama MOODLE_401_STABLE, mira si te funciona con los últimos cambios que he subido.

**Comment by tmas0** [comment]
Buenas @jmineroisyc,

Ahora siempre está bloqueado, sea el valor que tenga el field de Habilitar el timelimit.

Un saludo

**Comment by jmineroisyc** [comment]
Con la primera opción se desbloquea todo verdad?
![image](https://github.com/user-attachments/assets/11bc73b6-b8eb-4c30-998e-ceff06c45307)

**Comment by jmineroisyc** [comment]
Para aclarar, esto te pasa al crear quiz o al editar el quiz? 
Si puedes añadir aquí un vídeo de la prueba donde esta fallando igual veo algo que me de alguna pista.
Yo justo he descargado tu misma versión de moodle pero me va bien.

**Comment by tmas0** [comment]
Al crear. Lo genero y os lo mando.

**Comment by tmas0** [comment]
Aquí tienes el vídeo.

https://github.com/user-attachments/assets/f1edf6f8-fbbd-4c0e-a01a-4d0a04cb2228

Un saludo

**Comment by jmineroisyc** [comment]
Okay entonces  todo esta correcto
Al crear un quiz tiene que estar de esta forma: 
![image](https://github.com/user-attachments/assets/111c45ad-bebe-426c-8c3b-ee4bc60483e3)
Al editar un quiz es cuando puedes cambiar a las otras opciones de seccion, pregunta etc.
![image](https://github.com/user-attachments/assets/ba3dfee4-c024-440a-8156-1fd3eeccffc4)
Y al elegir por seccion, pregunta o pagina es cuando se bloquea el time ya que no lo vamos a usar.

Tiene que ser de esta forma si o si, ya que al crear el quiz no tenemos aún id de quiz, no tenemos secciones, ni preguntas ni nada.

Un saludo y gracias por el vídeo! 
Cualquier duda me preguntas.
